config/routes.rb
Ashwin::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :answers
  resources :questions do 
    member do
      post 'add_answer'
    end
  end
  root to: "static_pages#home"

  match '/signup', to: "users#new"
  match '/signin', to: "sessions#new"
  match '/signout', to: "sessions#destroy", via: :delete

  match '/help', to: "static_pages#help"
  
  match '/about', to: "static_pages#about"
  match '/contact', to: "static_pages#contact"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :description, :question_id
  belongs_to :question
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :name, :owner_id
  
  has_many :subdomains
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description
  has_many :answers
end

app/models/subdomain.rb
class Subdomain < ActiveRecord::Base
  attr_accessible :domain_id, :name, :owner_id
  belongs_to :domain
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  belongs_to :subdomain
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64  
    end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def create
  	@question = Question.new(params[:question])
  	if @question.save
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to :root
  	else
  		redirect_to :help_path
  	end


  end

  def add_answer
    @answer = Question.find(params[:id]).answers.new(:description => params[:description], :question_id => params[:id] )
    if @answer.save
      redirect_to @answer.question
    else
      redirect_to :help_path
    end
  end

  def show
    @q = Question.find(params[:id])
    #@a = @q.answers.create



  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
	def destroy
		user = User.find_by_remember_token(cookies[:remember_token])
		sign_out user
		redirect_to root_path

	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@question = Question.new
  	@question_all = Question.all

  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_filter :signed_in_user, only: [:edit, :update]
 # before_filter :correct_user,   only: [:edit, :update]
  #before_filter :admin_user,     only: :destroy
  def new
  	@user = User.new
  end
  def show

    if signed_in?
      @user = User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  def create
    @user = User.new(params[:user])
    
    if @user.save
      domain_now = @user.email.split('@').last
      if Domain.all.empty?

        domain_first = Domain.new(name: domain_now, owner_id: @user.id)

        #domain_first.users<<(@user)
        domain_first.save
        subdomain_domain_first = domain_first.subdomains.create(name: "Default", domain_id: domain_first.id, owner_id: domain_first.owner_id )
        subdomain_domain_first.users<<(@user)
        
      else
        d_flag = 0
        Domain.all.each do |d|
          if d.name == domain_now
           d.subdomains.find(1).users<<(@user)
           d_flag = 1
          end
        end  
        if d_flag == 0
          domain_new = Domain.new(name: domain_now, owner_id: @user.id)
          domain_new.save
          subdomain_domain_new = domain_new.subdomains.create(name: "Default", domain_id: domain_new.id, owner_id: domain_new.owner_id )
          subdomain_domain_new.users<<(@user)
        
        end
      end
      
    
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      sign_in @user
    else
      render 'new'
    end
  end

  def createi
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to :root
      sign_in @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def index
    @users = User.paginate(page: params[:page]) 
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User destroyed."
      redirect_to users_url
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "NoNamed"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user 
	end
	def signed_in?
    	!current_user.nil?
  	end
	def current_user=(user)
    	@current_user = user
  end
  def current_user
   	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  def sign_out(user)
  	cookies.delete :remember_token
  	self.current_user = nil
 	end
  def current_user?(user)
    user == current_user
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    NoNamed by Kavuluru Adithya
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "the NoNamed", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
_<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/questions/show.html.erb
<div class="row">
<div class="aside">
	<%= @q.description %> <%= @q.answers.size %>
	<% if not @q.answers.all.empty? %>
		<% @q.answers.all.each do |a| %>
			<div class="aside">
				<%= a.description %>
			</div>
		<% end %>
	<% end %>
	<%= form_tag({:controller => :questions, :action => :add_answer, :id => @q.id}, {:method => :post}) do |a| %>
	
		<%= text_field_tag "description", "description" %>
		<%= submit_tag "Add Answer" %>
	<% end %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
  <%= form_for(@question, :action => :create) do |f| %>
    
    <%= f.text_field :description %> </br>
    <%= f.submit %>
  <% end %>  
  </div>
  <% @question_all.each do |q| %>
    <div class="aside">
      <%= link_to q.description, q %></br>
      <div class="section">
      <%= q.answers.size %> Answers. 
      </div>
      ------------------------------------------------------------------------------------------------------
    </div>

  <% end %>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the NoNamed</h1>

    <h2>
      This is the home page for the
      NoNamed
      application.
    </h2>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user%>
  <%= link_to user.name, user %>
 </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %></br>
    
      </h1>
    </section>
        Member of Domain <%= @user.subdomain.domain.name %> </br>
        Member of Subdomain <%= @user.subdomain.name %>

  </aside>
  